### ISSUE TITLE
Something went wrong while checking for Script Extender updates

### ISSUE THREAD

**Issue by ultrasinan** [Norbyte/ositools#12]
The title pretty much sums it up.

I followed the same steps as my friend but I managed to get it to work with no issues while he gets that error. He tried disabling antivirus and adding to exceptions but didn't seem to work.

Any help would be appreciated.

**Comment by Norbyte** [comment]
Hi,

Could you check if you can download the update manually from your browser?
https://d1ov7wr93ghrd7.cloudfront.net/Release/Latest.zip
