### ISSUE TITLE
Game Crashes at Launch after V58 Update!

### ISSUE THREAD

**Issue by charlesbcqq** [Norbyte/ositools#120]
### Extender Version

v58

### Game Version

v3.6.117.3735

### Bug Summary

Game now crashes at launch after the script extender is updated to V58 just a few hours ago. I have done all troubleshooting. Restarted PC, did a clean game re-install, and also reinstalled the mod. Nothing helped. I just want to play the game.

Is there a way to just roll back to V57? I just want to play the game man.

### Links

![image](https://user-images.githubusercontent.com/126964362/222904922-53cc7dc0-c592-4776-b4e8-44d3825dd556.png)

**Comment by cepreu2github** [comment]
For anyone who wander here from Google or somewhere.
There is solution:
https://github.com/Norbyte/ositools/issues/119#issuecomment-1454747836

**Comment by LaughingLeader** [comment]
This should be fixed in the latest update: d756ad1b6e6ac1123e51f91a4aa73bd53b6fba54
