### ISSUE TITLE
Something went wrong while checking for Script Extender updates

### ISSUE THREAD

**Issue by LittleScav** [Norbyte/ositools#13]
This is the issue. it's an issue with my friend he has the exact same setup as I, however whenever he loads into the game it gives him this issue for the script extender. 
![74208404-afd7e100-4c40-11ea-930e-6fa091ef8df9](https://user-images.githubusercontent.com/63176233/78465245-f4bc4900-76c0-11ea-955e-6db8ab068a69.jpg)

**Comment by Norbyte** [comment]
Hi,

Could you check if you can download this file manually from your browser?
https://d1ov7wr93ghrd7.cloudfront.net/Release/Latest.zip

**Comment by Norbyte** [comment]
Hi,

You should create a folder called `OsirisExtender` in `%LOCALAPPDATA%` (the `AppData\Local` folder of your user), eg. `C:\Users\<Name>\AppData\Local\OsirisExtender`, and extract the contents of the .zip file directly into that folder.

An alternate solution is to rename `OsiExtenderEoCApp.dll` from the .zip file to `DXGI.dll` and copy it to `Divinity Original Sin 2\DefEd\bin`.

I'm looking into what goes wrong during the update process, but I can't see any obvious issue so far, so it is likely configuration specific.
