### ISSUE TITLE
Stuck on "Instantiate Level" when entering Act 2

### ISSUE THREAD

**Issue by box-admiral** [Norbyte/ositools#135]
### Operating System

Windows

### Extender Version

v59

### Game Version

v3.6.117.3735

### Bug Summary

Heavily modded playthrough, almost 80 mods. Game gets stuck while loading on "Instantiate Level" when attempting to finish Act 1 and get into Act 2, Reaper's Coast. I tried [enabling the Script Extender console](https://www.reddit.com/r/DivinityOriginalSin/comments/tqvp3n/enable_console_norbytes_script_extender/i2kqq74) but it just tells me the game is in "Sync" state and nothing else. Leaving it for a while results in a Script Extender crash, it asked whether to upload the crash dump and I clicked yes, I don't know where that file ends up but I can do it again and click no for a local copy if need be. If any other logs are required, do tell and I will provide.

In the meantime I will be disabling mods until something works. I wonder if there is a log/console I don't know about that would tell me what is going wrong.

Here are the lines after the ready check for going into the next act:
[GameStateChanged:SERVER] (Running) => (UnloadLevel)
[GameStateChanged:CLIENT] (Running) => (StartLoading)
[GameStateChanged:SERVER] (UnloadLevel) => (LoadLevel)
[GameStateChanged:CLIENT] (StartLoading) => (Idle)
[GameStateChanged:CLIENT] (Idle) => (UnloadLevel)
[GameStateChanged:CLIENT] (UnloadLevel) => (LoadLevel)
[OnTreasureItemGenerated] MyGuid(f52dad38-f93d-4a23-824f-fc1eaa4feb00) StatsId(ARM_Light_LowerBody) ItemType(Armor)
[OnTreasureItemGenerated] MyGuid(f52dad38-f93d-4a23-824f-fc1eaa4feb00) StatsId(ARM_Light_LowerBody) ItemType(Armor)
[GameStateChanged:CLIENT] (LoadLevel) => (SwapLevel)
[GameStateChanged:SERVER] (LoadLevel) => (Sync)

**Comment by box-admiral** [comment]
Turns out it was [Divine Scaling](https://steamcommunity.com/sharedfiles/filedetails/?id=1621070446) causing this issue. I've left a comment on their page, but I don't know how helpful I can be.

If there is any info/logs I could provide to the Script Extender team or the dev of Divine Scaling that could fix this issue, I'd like to do so. But if it's not worth the time pursuing, feel free to close this and move on. My issue has, technically, been solved.

**Comment by box-admiral** [comment]
Actually the mod just doesn't work at all in Act 2. Disabled mod, moved into Act 2, reenabled mod, loaded save and same Instantiating Level problem. Just gonna close this and keep the comment on the mod page.

**Comment by VaelophisNyx** [comment]
had this pop up randomly today, with mods that worked for an entire playthrough literally two days ago-
no updates to anything involved, and now I can't even connect at all
