### ISSUE TITLE
Game crashing when saving (manual, quick, auto) even without a single mod.

### ISSUE THREAD

**Issue by hoaihoai3** [Norbyte/ositools#17]
I've had a severe problem where every time I save the game there is a chance it would just crash to desktop. I thought it was the mods, then the cloud sync, then my graphics settings, running as administrator. I even moved the save location away from my system drive. 

After 2 days of frustration, turns out all it took was removing this tool. 
Can you look into it? I love that it reduces load time by a lot and allow me to use a great new mod called Divinity Unleashed.

**Comment by Norbyte** [comment]
Did the game produce any crash dumps (`CrashDump_date.dmp` files in `DefEd\bin\`)? If so, could you upload the latest one here?

**Comment by hoaihoai3** [comment]
I reinstalled my game, updated my mods, stopped using nexus (manual using steamworkshopdownloader), and also removed the Lizard Recolor and Elf Model mods. I have been able to save multiple times without crashes so far. The crash dumps are gone when I uninstalled my game though sorry.

Thank you for this amazing script extender.

**Comment by Kara-bit** [comment]
Having the same issues, not sure what to do, tried things such as running as admin (which seemed to help for 10 minutes) and removing all mods, but every so often the game will crash on save. If it helps any, i've been able to run a similar game (Baldurs gate 3) without this issue. Couple of the crash dumps below in zips: 
[CrashDump - 01-10-2021 18h 53m 05s.zip](https://github.com/Norbyte/ositools/files/5793163/CrashDump.-.01-10-2021.18h.53m.05s.zip)

[CrashDump - 01-10-2021 16h 22m 42s.zip](https://github.com/Norbyte/ositools/files/5793161/CrashDump.-.01-10-2021.16h.22m.42s.zip)

**Comment by Norbyte** [comment]
Hi,

Sorry for the late reply I was away for a few days.
I checked your crash dump, however it was from an old game version (`3.6.58.1306`). 
I'm not sure what caused your crash since I only have debug databases for the latest game verison -- `3.6.69.4648`. You should update your game tho, as 3.6.58 contains lots of bugs related to summons and statuses that may crash your game quite frequently.
