### ISSUE TITLE
Error starting game Divinity original sin2 de

### ISSUE THREAD

**Issue by greatrush** [Norbyte/ositools#18]
Hi, Norbyte, if there is a Script Extender dll file in the bin folder, the game produces an error after launch: EoCApp.exe - No entry point was found (The entry point to the DXGID3D10CreateDevice procedure was not found in the Dll library dxgi.dll).  Then: Failed to create rendering device!  (The application falied to create the rendering device. Please make sure you meet the minimum specifications! (DX11 compatible GPU with the latest drivers installed). This error assumes that my system does not support DirectX11, but it is not! Without this dll file  the game starts without errors. GoG version.

**Comment by Norbyte** [comment]
Hi,

Which version of the updater did you download? This was an issue in older versions but should be fixed in v38.1.
--> https://github.com/Norbyte/ositools/releases/tag/v38_1

**Comment by Norbyte** [comment]
Actually, looks like I haven't published the version with the Windows 8 fix yet, so here it goes:
https://github.com/Norbyte/ositools/releases/tag/v38_2

Can you check if the game works with this version?
