### ISSUE TITLE
Error when loading script dll extender: 1114

### ISSUE THREAD

**Issue by lou00011** [Norbyte/ositools#19]
I ran into this error on Main menu. I tried adding the script twice, still the same error.
validating game files yield no result.

**Comment by Norbyte** [comment]
Hmmm, I've never seen that error code before. What Windows version are you using?

**Comment by lou00011** [comment]
@Norbyte I haven't had a chance to test it further. Will report back once I do. Sorry about that.

**Comment by lou00011** [comment]
@Norbyte OK that worked. Thanks.
