### ISSUE TITLE
Error when launching game with Script Extender

### ISSUE THREAD

**Issue by yanih7** [Norbyte/ositools#20]
My friend is having issues starting his game with the Extender and can only get it to work with the original system dxgi file. The moment he replaces it with the Script Extender, he gets this error. He has redownloaded the file multiple times and it gives him the same issue every time. It's very weird because I'm using the Script Extender with no issues and installed it exactly the same way he did. Would really appreciate some help with this, thank you!

![dx](https://user-images.githubusercontent.com/65488502/82141139-dcedee00-9844-11ea-8e30-6b00b0641674.png)

**Comment by zepinguoin** [comment]
Hello, It's been a week, and I'm also having crash at game launch (Defenitive edition, GoG version, tried to launch with Vortex, GoG launcher and directly through the exe). 

As soon as I hit the loading screen (the 1st one after the Larian logo) the game closes with no error whatsoever (just have the Larian report prompt to send their team but with no helpful information). 

I updated to latest drivers (Nvidia gtx 1080) ... no changes. As soon as I remove the DXGII.dll the error goes away.....but I need it to play Divinity Unleashed mod (awesome btw) 

Please advise

**Comment by Norbyte** [comment]
@yanih7 I've published v38.2 which should fix your issue:
https://github.com/Norbyte/ositools/releases/tag/v38_2

@zepinguoin I'll need a crash dump (.dmp file) from the `DefEd\bin` directory to check what goes wrong, without that I can't really help.

**Comment by yanih7** [comment]
> @yanih7 I've published v38.2 which should fix your issue:
> https://github.com/Norbyte/ositools/releases/tag/v38_2

@Norbyte That's awesome I can confirm it's fixed the issue, thank you very much!

**Comment by zepinguoin** [comment]
Hey Norbyte, 

First off, thanks for answering, feels good not to be left aside. Forgot to mention that I don't even have any dump file in my DefEd/bin directory ! I'm gonna check with the new version tonight to see whether there is a change. I'll let you know. 

Even though I have not tempered with the installation of the game, is there a way that the dump file could be either hidden or turned off ? 

Talked yesturday with a friend of mine who told me that it was really odd that I didn't have any dump file/log. That it might suggest that the dll would not be the issue.... but removig it is the only way I got the game to launch :'(. 

Keep you posted

**Comment by Norbyte** [comment]
The Larian error reporting thing deletes the dump file I think. Just launch the game directly via EoCApp.exe and the dump files will be kept.

**Comment by zepinguoin** [comment]
Still no dump file Oo with the exe. Just put the new version you uploaded yesturday. And it's fixed... Have no idea what went wrong but thank you anyway <3. Still tho, weird that I have no dump. Do I need the Ositools ? I just put the dll in the bin folder. Maybe I did something wrong ?

**Comment by zepinguoin** [comment]
Well I spoke too fast. Still crashing, sometimes it works but most of the time it crashes (like I have to launch the game 20 times a row to get to the main menu, but not consistently). I still have no crash report. in the bin file. 

I'm lost :'(

**Comment by zepinguoin** [comment]
Finally got to get a dmp file ! I don't know how I can send it to you though :S

**Comment by zepinguoin** [comment]
I think that I get a dmp file when I try to load a game (which happens if I can get 1 times out of 20 times), This is why I didn't have any before. Maybe the one I have now (I could get to the menu and loading a game unsuccessfully) can help you out.

**Comment by Norbyte** [comment]
Hmm, it might be a crash reporter issue. Do the following:
Create a file named `OsirisExtenderSettings.json` in `DefEd\bin` with the following contents:
```json
{
  "EnableExtensions": true,
  "CreateConsole": true,
  "SendCrashReports": false
}
```

Then try to launch the game again and check if a .dmp file was created this time.

**Comment by zepinguoin** [comment]
Hmm so a couple of new things here : 
- Before placing the json file (didn't see your post back then), I managed to get a dmp file. Which appears to be a binary (when I open it in a text editor I get weird symbols). It's quite difficult to get, coz it seems that even though I launch the game vie the exe, Larian report pops up either way, thus I guess deleting the .dmg file. Still I've saved it, but I don't know how to get it to you (and obviously pasting weird symbols won't help). 
- I placed the json file as you mentioned. Still no dmg file coz I couldn't get the Larian report not to pop up. But I see the console opening up. As I have a dual screen setup, I managed, just as the game launched, to place it on my 2nd monitor. When the game crashed the console also goes away. So I spammed my screenshot key to get a hold of the console. But it seems like the error doesn't have time to get through the console before the game crashes and the console disapears. I only managed to get this : 

![Picture1](https://user-images.githubusercontent.com/65489285/82437736-3437cc80-9a98-11ea-8409-3b0f310da03f.png)

- As I loose focus on my desktop while launching the game (fullscreen), I spammed the game. As I mentioned before, sometime I can get it to work, even though it's not stable. Sometimes it passes the 1st loading screen and crashed in the menu, sometimes it crashes when loading an actual save (regardless if a mod is activated or not). I managed to get into the settings and set it to Borderless /window mode and the game no longer crashes .... go figure.

**Comment by Norbyte** [comment]
You can upload the dump here -- https://send.firefox.com/

**Comment by zepinguoin** [comment]
Just did, here's the link https://send.firefox.com/download/f0679858c131b8c9/#pdR_3xrpQOc51v-HeHLBYw

**Comment by Norbyte** [comment]
Looks like it crashed while loading `playerprofiles.lsb`, it isn't clear why though.

Stack:
```
0x0000000141DE7724 (???)
eoc::EocProfileManager::LoadProfiles+0x501
App::LoadConfig+0x91
BaseApp::Start+0x179
WinMain+0x1C0
```

**Comment by zepinguoin** [comment]
I don't know what to make of this hmm. Thanks for looking though.
