### ISSUE TITLE
Game crash at this part every time. 

### ISSUE THREAD

**Issue by lordseppe** [Norbyte/ositools#22]
crashes every time here. i get a script extender error. when disabling the extender it still crashes. any clue? or any way on how i can see what caused the crash?
![crash](https://user-images.githubusercontent.com/66175471/83333239-ce212580-a29f-11ea-884d-0a7667abdac7.PNG)

**Comment by lordseppe** [comment]
its after fighting in the arena on act 3 i think it is. when the red skelly man appears it crashes

**Comment by Norbyte** [comment]
Do you have any crashdumps in `Divinity Original Sin 2\DefEd\bin`? (`CrashDump - 05-20-2020 16h 16m 31s.dmp` etc.)
When the game crashed, did it just exit or did you get a crash reporting prompt?

**Comment by lordseppe** [comment]
the game just closed leaving behind a lilttle error window of the script extender. today i learned that the crash was caused because of the mod 'Gravewalker Class DE'. the crashed only accured onces before but was able to avoid it. but this part of the game was unavoidable. disabling the mod solved the issue. i assume the crash is caused because the familiar figure copies the looks of the player. maybe having an item of that mod was not able to be copied and caused the crash. dont know if this helps or anything, the problem for me is resolved. if you need more info, feel free to ask
