### ISSUE TITLE
file not being recognized

### ISSUE THREAD

**Issue by zordye** [Norbyte/ositools#23]
i downloaded the script extender for a mod the other day and it worked just fine but now my game is acting like the script extender isn't in the files and can' read it. so now my mod doesn't work anymore

**Comment by Endaii** [comment]
I have a similar issue. I get this message anythim I run the game. I copy pasted the command line for the the launch option, so I can't have typed anything wrong.
![Untitled124](https://user-images.githubusercontent.com/78086324/105992613-59db9380-6073-11eb-9f19-86931eef9b71.png)

**Comment by Norbyte** [comment]
You only have to edit the launch options if you're on Linux; on Windows you don't have to change launch options at all.
