### ISSUE TITLE
achievements not being auto enabled

### ISSUE THREAD

**Issue by Hathcyn** [Norbyte/ositools#24]
After the new update for gift bag 5, achievements aren't working with the extender installed and running, even with the latest tweaks.

**Comment by Norbyte** [comment]
Hi,

Thanks for the report, I'll look into it.

**Comment by Norbyte** [comment]
Hi,

I've released a fix; can you check if achievements work now?

**Comment by Hathcyn** [comment]
I'll hop on now. Do I need to pull the new build or does it update? Sorry I actually just started using the Extender haha.

**Comment by Norbyte** [comment]
It should updates automatically

**Comment by Hathcyn** [comment]
It does in fact, and achievements are working! Thanks for all the work you do, and for being alarmingly responsive.
