### ISSUE TITLE
Error initializing script extender

### ISSUE THREAD

**Issue by supersonic2803** [Norbyte/ositools#25]
Hello! Ever since the new gift bag, I've been having issues towards the script extender- I've tried reinstalling the game. Someone else seemed to have had this error, but it was to do with an achievement enabler I don't have, I went through some of the motions of that thread in order to try and help out, i've not added or changed any mods, and the only thing I can think of that's different is this new gift bag.
![issues2](https://user-images.githubusercontent.com/67062766/84913670-aeb53580-b0b2-11ea-9a05-6891a12b7da5.png)
![issues](https://user-images.githubusercontent.com/67062766/84913754-c55b8c80-b0b2-11ea-87f1-50485518b2b0.png)

**Comment by Norbyte** [comment]
Hi,

Can you try deleting the contents of `%LOCALAPPDATA%\OsirisExtender`?
There is an updater bug where the update sometimes fails to fetch if more than one instance of the game is open or the file is locked when the update occurs, so you could be left with an old version in these cases.

**Comment by supersonic2803** [comment]
Doing that has left me with a different error, this time. My load times have been much longer then usual, though I just assumed that was due to the mods. something like 3-5 minutes sometimes
![image](https://user-images.githubusercontent.com/67062766/84920872-a6adc380-b0bb-11ea-981c-688359f700a3.png)

**Comment by supersonic2803** [comment]
Solved the problem! Noticed someone else had this error in the past, and you provided the link to manually download the latest version. Decided to do that, and it works fine now. Thank you for your time!
