### ISSUE TITLE
Script extender is not work normally

### ISSUE THREAD

**Issue by napoonia** [Norbyte/ositools#26]
After trying many times with installing .dll by making operation according to the given tutorial or installing it automatically via Divinitymodmanager, it seems not to work for me..After some test, it can be sured that the achievements have been still locked and my loading screen before the Main Menu appears doesnot change. Maybe it is just a update-problem, i guess. So, can you provide the lastest complete version of the extender directly instead of a updater?

**Comment by napoonia** [comment]
![ss1](https://user-images.githubusercontent.com/67101244/85019491-80625380-b1a1-11ea-9150-e2413a4da3e7.jpg)
like this....

**Comment by Norbyte** [comment]
Hi,

Depending on how you downloaded it you might need to unblock DXGI.dll before the game can load it.
See:
https://winaero.com/blog/wp-content/uploads/2015/10/Windows-10-unblock-a-file.png

Also make sure that it's in DefEd\bin, not the classic bin folder.

**Comment by napoonia** [comment]
![ss](https://user-images.githubusercontent.com/67101244/85053054-8883b880-b1cc-11ea-90fd-dacbda87fb42.png)
thanks for you help, but my file has never been locked and  the problem has still been here.

**Comment by Norbyte** [comment]
Could you ping the host `d1ov7wr93ghrd7.cloudfront.net` from the command line?
There is a known issue where updating fails if your ISP has wonky IPv6 support and I'd like to find out _why_ the update actually fails (if it fails at all).

Also, could you download this DXGI version and paste the console output here:
[DXGI.zip](https://github.com/Norbyte/ositools/files/4801129/DXGI.zip)

**Comment by napoonia** [comment]
![19090338](https://user-images.githubusercontent.com/67101244/85086440-31520800-b20d-11ea-912f-e4ff7877b633.png)

**Comment by napoonia** [comment]
And how can i get the output of script extender debug console ?? i use the file you produce and then lauch the game, but nothing happens.....

**Comment by napoonia** [comment]
And how can i get the output of script extender debug console ?? i use the file you produce and then lauch the game, but nothing happens differently..

**Comment by napoonia** [comment]
look like the file is never loaded when game is lauched......

**Comment by napoonia** [comment]
look like the file is never loaded when game is launched......

**Comment by Norbyte** [comment]
One alternative you can try is downloading this:
https://d1ov7wr93ghrd7.cloudfront.net/Release/Latest.zip

Then extract it to DefEd\bin and rename OsiExtenderEoCApp.dll to DXGI.dll.
Although if the previous one didn't load then I suspect this one won't either.

**Comment by napoonia** [comment]
Thanks again for your help. However, it doesn't work also... I have no idea, and there are some person who meet the similar problem. Maybe my PC not match some certain requirments so that the extender cannot be installed normally...

**Comment by Norbyte** [comment]
What Windows version are you using?
Could you try running this command: `rundll32 "E:\Steam\steamapps\common\Divinity Original Sin 2\DefEd\bin\DXGI.dll" test` and copy the message you receive?

**Comment by napoonia** [comment]
Win10...
running this command in cmd?
![620190740](https://user-images.githubusercontent.com/67101244/85200364-5dfb4200-b329-11ea-90e1-7ff2707ee405.jpg)

**Comment by Norbyte** [comment]
Yes that, but don't forget to add ` test` at the end.

**Comment by napoonia** [comment]
Thank for your help very much!!! The problem is solved after i update my win10.... Now, the file have been loaded successfully...
