### ISSUE TITLE
Unable to extract Script EXtender update package

### ISSUE THREAD

**Issue by 335137** [Norbyte/ositools#27]
I just download lastest Release v38.2 and extract it to the right path for Divinity Unleashed.
But when I open the game,a"Osiris Loader Error" showed up and said:
Unable to extract Script EXtender update package.HRESULT 0x80004005
And when I try to load Divinity Unleashed，inevitably fail.
From this line,I thought it might be missing something.
So I download this:https://d1ov7wr93ghrd7.cloudfront.net/Release/Latest.zip,
which you post at other's issue,and I just manually download and extract it 
Wow,Divinity Unleashed successful loaded
But I still get that error everytime I open the game.
How may I remove this?

**Comment by Norbyte** [comment]
Though this is an old issue, the zip extraction method was reworked a few months ago, so this shouldn't be occurring anymore.
