### ISSUE TITLE
Script is loaded but achievements are not getting unlocked

### ISSUE THREAD

**Issue by nathanpovo** [Norbyte/ositools#28]
Hi,

I am having a similar issue to #24 and #26 

I have successfully loaded the DXGI.dll in the game
![image](https://user-images.githubusercontent.com/17831160/87073006-fc8a0d00-c21c-11ea-8e9f-74754c06095b.png)
but achievements are still not getting unlocked.

The dll file is not blocked (even when blocked the game still loaded the dll successfully), I can ping `d1ov7wr93ghrd7.cloudfront.net` without issues,
![image](https://user-images.githubusercontent.com/17831160/87073099-25aa9d80-c21d-11ea-939c-9d3b82b89029.png)
and when trying the `rundll32 "E:\Steam\steamapps\common\Divinity Original Sin 2\DefEd\bin\DXGI.dll" test` I get the following message:
![image](https://user-images.githubusercontent.com/17831160/87073273-6b676600-c21d-11ea-9fad-fad23116ffdf.png)

**Comment by Norbyte** [comment]
That's rather strange. 
Are you using only workshop mods or built-in gift bags as well?
In addition, are you using the achievement enabler from Nexus?

**Comment by nathanpovo** [comment]
I am only using the built-in gift bags.

I was using the achievement enabler from Nexus but I removed the files by repairing the game files using Steam.

**Comment by Norbyte** [comment]
Did you check achievements before or after removing the Nexus achievement enabler?
Please note that the two enablers are incompatible, so if the Nexus one is loaded then the script extender achievement feature will be unavailable. Since the one from Nexus no longer works since Gift Bag 5 this means that you won't get achievements until it's removed.

**Comment by nathanpovo** [comment]
I had checked it after removing the mod.

I just checked the files to make sure the enabler from Nexus were removed but they were still there. Apparently, Steam's file integrity verification system doesn't actually check the content of the files.

Now that I've manually removed the Nexus enabler the achievements are getting unlocked.

Thank you for your help and sorry for any inconvenience caused.
