### ISSUE TITLE
Is there a way to install this for the mac version of DOS2?

### ISSUE THREAD

**Issue by shabatin** [Norbyte/ositools#3]
The installation path (/DefEd) doesn't exist in the mac version's file tree, and I'm not sure it would work anyway? Confirmation would be appreciated!

**Comment by psisavant** [comment]
Windows .dll files are not going to be processed by macOS (which employs .dylib files for similar purposes, though the architecture differs) unless the mac version is not native and actually employs a wine/proton-like abstraction-layer as a 'wrapper' of sorts.
Tested the aboventioned 'not-emulator' on a linux rig with... somewhat expected results - attempting to use the provided dxgi.dll in the 'emulated' environment simply results in the game (the Osyris component to be exact) complaining about being unable to read the file in question.

**Comment by N0Br41nZ** [comment]
Did you get to the bottom of this by any chance? :)

**Comment by shabatin** [comment]
The mac version is done via Wine yes, not native. To be honest psisavant's suggestion sounds complicated and I wouldn't know where to start with implementation, so sounds like a general nope for mac support

**Comment by psisavant** [comment]
>so sounds like a general nope for mac support
Truth to be told, due to time shortages, I haven't tried using DXGI without dxvk >.>.

**Comment by Norbyte** [comment]
For some reason I didn't get any notification about this issue, sorry about that :(

Currently macOS is not supported, and is unlikely to be supported in the short term. It would need a completely separate dylib injection process, separate loader, a new library for hooking functions, I'd have to recreate my symbol database from scratch, etc etc.
Essentially, it would take roughly the same amount of effort it took to create the Windows version.

**Comment by shabatin** [comment]
as mentioned yes the mac version is via wine. happy to help test if you can provide what i need and describe how to use it…

**Comment by Norbyte** [comment]
What does the file tree of the Mac version look like?
It'd be the best if you could put it in the directory where EoCApp.exe is.

**Comment by cameroncondry** [comment]
It doesn't look like EoCApp.exe even exists when you install on a macOS using Steam. Here is the file structure:
<img width="353" alt="Screen Shot 2020-01-31 at 10 29 23 AM" src="https://user-images.githubusercontent.com/2709431/73551566-9e0e6680-4414-11ea-98c0-0393c143dddb.png">

**Comment by Norbyte** [comment]
Looks like it's a native mac OS app, I see no traces of Wine/Proton there.
In that case I'm afraid the macOS version of DOS is not supported currently.

**Comment by depressed-pumpkin** [comment]
Norbyte, is there any way you could possibly make a separate mac version of this? Because all the mac users out there (including me 😉 ) would really appreciate it if you could

**Comment by LaughingLeader** [comment]
Closing this since it's safe to say MacOS won't be supported.
