### ISSUE TITLE
SyncStat() and skill-tooltips

### ISSUE THREAD

**Issue by Shresht7** [Norbyte/ositools#31]
So, I noticed a while ago that `Ext.SyncStat(skillName)` breaks the _memorization-requirement tooltips_ of `skillName`.  The tooltip adds a new row to requirements with each subsequent `SyncStat` call.

|Before SyncStat|After 3 SyncStat|
|-----------------|-----------------|
|![image](https://user-images.githubusercontent.com/59516096/87879249-3cb07300-ca07-11ea-9caa-f22577e04a32.png)|![image](https://user-images.githubusercontent.com/59516096/87879278-46d27180-ca07-11ea-9f94-5a0e732a6757.png)|

Worth pointing out that this happens regardless of any stat-modification. In the example given in this issue, I've used `SyncStat` on an _unmodified_ `Projectile_Fireball`. `SyncStatPersistence` doesn't have any effect except for the fact that the tooltip stays bugged if persistence is `true`. Also worth noting that this issue does not occur if stat-modification is done during `ModuleLoading` client-side, as stat-synchronization isn't needed/called. 

At first, I thought that the issue was with the `MemorizationRequirements` attribute, however, `Ext.Print(Ext.JsonStringify(Ext.StatGetAttribute(skillName, MemorizationRequirements)))` only returned one element both before and after `SyncStat`.

Now, recently, I wrote a console-command to iterate over all possible attributes of a given stat and print all their values. I noticed that it's not `MemorizationRequirements` that gets bugged, but the `Requirements` attribute (which apparently is different from a third _"`Requirement`"_ attribute). Every time `SyncStat` is called, `Requirements` appends another stack.

![YtU401eCLH](https://user-images.githubusercontent.com/59516096/87879296-6a95b780-ca07-11ea-8f02-bfbef1dbac21.gif)

Additionally, You may have noticed from the Fireball tooltip images that `SyncStat` also breaks `TranslatedStringKeys` like `displayName`. This is again something I've only seen caused by `SyncStat`. I haven't looked too deeply into this, but the string can still be retrieved using `Ext.GetTranslatedStringFromKey("Projectile_Fireball_DisplayName")`, it just doesn't like showing up on the tooltip.

While my mod offers the option to dynamically edit stats and then synchronize them once game-session has begun, it defaults to saving these edits to apply during the next `StatsLoaded` event. This and the fact that `SyncStatPersistence` defaults to `false` mean that I don't have to deal with both these issues all that much. I'm not sure if this is something that can be fixed from your side, but I thought I'd let you know anyway.

**Comment by Norbyte** [comment]
I've looked into it and both the requirement duplication bug and the incorrect translated string bug should be gone now!

**Comment by Shresht7** [comment]
That's great, thank you!
