### ISSUE TITLE
Divinity on Gog, no v50 text at bottom of menu

### ISSUE THREAD

**Issue by housecakes** [Norbyte/ositools#34]
Playing with the conflux mod on div:os2 and now getting a message in every load that there's an issue with the add-ons. I've redownloaded the mod and this extender multiple times, disabled my firewall to allow potentially blocked extender update, etc.

The main menu shows that i'm running "v3.6.69.4648" with no mention of the script extender. If there's any way for you to just post the v50 on here, I'm not sure what else to do to force an update. Maybe the script extender text doesn't show on Gog? Not sure how to check any of that, but I may just have to switch to steam

**Comment by Norbyte** [comment]
Hi,

Could you post the exact error message for the issue with the add-ons?
Also, you'll only see v50 in the main menu if you use at least one extender-enabled mod. If for some reason your .pak is corrupted then you won't see v50 in the menu at all. However, it should still show up on the main menu loading screen.

**Comment by housecakes** [comment]
"We were unable to create a working Story. Your add-on setup might be invalid"

There's no extender or mod version number on any loading screens. I've re-downloaded everything multiple times, the mod creator is also trying to help me. He uses Gog and doesn't seem to have any issues with his most recent version, but nothing I've done has fixed it so not sure where I'm going wrong. 

Do I need to have my firewall disabled when I start the game to allow the extender to update?

**Comment by Norbyte** [comment]
Could you try replacing the updater with this DLL and see if it updates?
[DXGI.zip](https://github.com/Norbyte/ositools/files/5086230/DXGI.zip)

**Comment by housecakes** [comment]
I figured out the issue. I had the extender in the game folder within My Documents instead of within Program Files. Prior to this most recent update, it worked fine, but maybe something with v50 changed the way it interacts.

Again, I'm playing on Gog, so I wasn't sure of the file path for the extender placement. If you want to add a message about that on the main download page, it may prove helpful for others
