### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by Glorfinion** [Norbyte/ositools#35]
An error pops up during the second half of the loading screen, saying that it couldn't update and to check my internet connection. Is this maybe due to the recent game update? I'm wondering if I should wait for an update, or just give up and play with mods that don't require the script extender.

**Comment by Norbyte** [comment]
Hi,

Could you ping the host `d1ov7wr93ghrd7.cloudfront.net` and post the result? (Including the IP address that it resolved to)
eg.
```
Pinging d1ov7wr93ghrd7.cloudfront.net [52.84.107.209] with 32 bytes of data:
Reply from 52.84.107.209: bytes=32 time=6ms TTL=242
Reply from 52.84.107.209: bytes=32 time=6ms TTL=242
```

**Comment by Glorfinion** [comment]
So I'm not going to lie, I don't really understand what you mean. At this point i'm thinking of just giving up and playing without the extender. I do have a question though, do you always need to update the script extender after a game update?

**Comment by LaughingLeader** [comment]
You can ping the address by opening up a command prompt (Windows key + R, then enter `cmd` and hit enter or click OK).
Then in the command prompt, copy/paste this text into the command prompt and hit the Enter key on your keyboard:
```
ping d1ov7wr93ghrd7.cloudfront.net
```
Finally copy/paste the text the command prompt resulted in here, so Norbyte can see what IP the host address resolved to, like this:
```
ping d1ov7wr93ghrd7.cloudfront.net

Pinging d1ov7wr93ghrd7.cloudfront.net [143.204.26.77] with 32 bytes of data:
Reply from 143.204.26.77: bytes=32 time=33ms TTL=246
```

**Comment by Norbyte** [comment]
Could you try replacing the updater with this DLL and see if it updates?
[DXGI.zip](https://github.com/Norbyte/ositools/files/5086230/DXGI.zip)

If not, could you paste the console output here so I can see why it fails?

**Comment by Glorfinion** [comment]
Hey, so turns out I had to disable my Windows Firewall and that allowed the script extender to update. Even after enabling it again it still works without a problem, I just needed to disable it for the first time.

**Comment by Norbyte** [comment]
Glad to hear that this was resolved.
