### ISSUE TITLE
Downloaded extender console to try to track a problem, now it won't go away

### ISSUE THREAD

**Issue by housecakes** [Norbyte/ositools#36]
![unknown](https://user-images.githubusercontent.com/69732807/90950004-8c1d0100-e402-11ea-92fe-df7c15760fce.png)

I've deleted the .json file, searched my computer for it and i don't know where it's running from. Maybe I just need to enter a command to determine its location or remove it, but I'm relatively illiterate with this stuff.

**Comment by housecakes** [comment]
Downloaded this and it caused the game to hard lock my computer on loading into a multiplayer game. 

Does this debug version create log files? My only concern is it if it's storing log files somewhere that are growing and taking up needed memory. If it's just a console for tracking without creating files, then i don't mind sticking with this

**Comment by Norbyte** [comment]
No, the updater itself doesn't create logs. The extender may do, although those are only created on a failed compile and are typically 1-2 KB in size.
