### ISSUE TITLE
Script extender wont update to v52

### ISSUE THREAD

**Issue by Corbsterp** [Norbyte/ositools#38]
The script extender won't auto update to v52 for me. I've tried reinstalling the .ddl from the v52 download link, but it keeps re-d
ownloading v51.

**Comment by Norbyte** [comment]
The .dll is just the updater, it isn't the extender itself. The v52 updater was released before the actual v52 extender, so it might seem like it downgrades itself, but it doesn't.

v52 should be released now, so if you restart the game it should show v52.

**Comment by Corbsterp** [comment]
Oh that makes sense, thanks!
