### ISSUE TITLE
Cannot load extender with v52 updater

### ISSUE THREAD

**Issue by Aeranuth** [Norbyte/ositools#40]
Failed to check for Script Extender updates. make sure you're connected to internet and try again.

Win10
Using steam definitive edition.

**Comment by Aeranuth** [comment]
can you provide a way to download extender manually without the updater? 

it turns out my isp is blocking your server ip

**Comment by buzzcut-s** [comment]
You can get it from d1ov7wr93ghrd7.cloudfront.net/Release/Latest.zip

**Comment by HEXEPAHYC** [comment]
> You can get it from [d1ov7wr93ghrd7.cloudfront.net/Release/Latest.zip](here)

I must place this DLLs to bin folder?
