### ISSUE TITLE
Friend failing to join after v53 update rolled out

### ISSUE THREAD

**Issue by VastrixL** [Norbyte/ositools#41]
Upon loading the game today  and seeing that on the main menu we were running v53 and trying to continue our save, we get the error that his mod hash doesn't match the servers(which would be mine I'm assuming). The commit version we have is the one from today that starts with 000e36f. But I saw you made a more recent commit starting with 7e9d8a9 that addressed hash issues. I was wondering if that version hasn't rolled out to fix our issue or if there is some other way to fix this on our side.
![EoCApp_cURxjas6Lx](https://user-images.githubusercontent.com/13716038/96494554-82eabd80-1214-11eb-8b8a-241d027de32a.png)

**Comment by Norbyte** [comment]
Hi,

It should be rolled out now.
There are two cases that the commit (and the one before that) fixes:
1) is mods that use path overrides to replace files in the base game may cause inconsistent hash values (eg. LeaderLib)
2) is that reloading mods did not clear the hash cache so changing a mod between game loads still used the old hash value.

I haven't seen any mods that override `Shared` files via path overrides, though it may happen.
Can you check again?

**Comment by VastrixL** [comment]
Sadly still happening, and we are now on commit 7e9d8a9 so really unsure why. It was working yesterday and we haven't changed any mods. We've also reinstalled the extender and all of our mods just to make sure and still no luck. Very confusing.

**Comment by Norbyte** [comment]
I've temporarily disabled the hash checks until we can figure out what's wrong with them, so only version numbers will be checked in the meanwhile. It should be working properly now!

**Comment by VastrixL** [comment]
It indeed is working properly now. Unsure what specifically was going wrong with hash checks but that does seem to have been the issue.

**Comment by Norbyte** [comment]
Good to hear!
