### ISSUE TITLE
Build Story script failure

### ISSUE THREAD

**Issue by Toijiro** [Norbyte/ositools#47]
Hi Norbyte,
I'm quite new to modding Divinity 2, so I've run to some problems when trying to add some of your Orisis calls.
I've installed `DXGI.dll` and made a configuration file named `OsirisExtenderSettings.json` inside `Divinity Original Sin 2\DefEd\bin`
```json
{
  "EnableExtensions": true
}
```
Then I added `OsiToolsConfig.json` to my mod folder with the following content:
```
{
  "RequiredExtensionVersion": 52,
  "FeatureFlags": [
    "OsirisExtensions",
    "Lua"
  ]
}
```
After that I opened the Story Editor, generated the defininitions and created my goal. When I tried to build, all `NRD_*` calls gave me warning saying `fact does not start with DB_`. Did I miss something along the way? Could you help me please?

**Comment by Norbyte** [comment]
Hi,

If you'd like to use the extender in the editor, you need to add DXGI.dll to the editor folder as well (`steamapps\common\The Divinity Engine 2\DefEd`). After that, generating definitions should add the new functions to `story_header.div`.

**Comment by Toijiro** [comment]
I knew it was something simple, thanks Norbyte ;)
