### ISSUE TITLE
Script Extender and ReShade 1.1.0 with SweetFX 2.0.

### ISSUE THREAD

**Issue by czkevin36** [Norbyte/ositools#49]
It is possible to somehow combine Script Extender with ReShade 1.1.0 with SweetFX 2.0? Both programs contain the DXGI.dll file.

**Comment by Norbyte** [comment]
Hi,

Rename ReShade's DXGI.dll to `DXGINext.dll` and it will automatically chain-load after loading the script extender.

**Comment by czkevin36** [comment]
Thank you very much for the advice. It works perfectly.
