### ISSUE TITLE
Script Extender updates error

### ISSUE THREAD

**Issue by Marksway** [Norbyte/ositools#5]
Auto update don’t work:
![Error](https://user-images.githubusercontent.com/61252259/74876012-42306100-5374-11ea-82c4-a9a537e92ebf.png)
So, URL “https://d1ov7wr93ghrd7.cloudfront.net/Release/Latest.zip” open and saved (Latest.zip).

Could you please describe the ways (directories) for manual unpacking Latest.zip?

**Comment by Norbyte** [comment]
Hi,

You should create a folder called `OsirisExtender` in `%LOCALAPPDATA%` (the AppData\Local folder of your user), eg. `C:\Users\<Name>\AppData\Local\OsirisExtender`, and extract the contents of the .zip file directly into that folder.

**Comment by Marksway** [comment]
Thank you. Extender and mod are now working.
