### ISSUE TITLE
not an issue per say, just didnt know where to ask this

### ISSUE THREAD

**Issue by kajikaferus** [Norbyte/ositools#51]
Could you upload this to the steam workshop? it's the only way i can download them as i use nvidia geforce now to run it

**Comment by Norbyte** [comment]
Hi,

The script extender is not a "normal" mod, as it contains native code and doesn't install in the normal mod directory. Because of this, it cannot be put onto the workshop (it simply wouldn't function as a workshop mod), sorry.

**Comment by kajikaferus** [comment]
Oh alright, darn thanks
