### ISSUE TITLE
Norbyte's Script Extender with Reshade ?

### ISSUE THREAD

**Issue by horizertical** [Norbyte/ositools#52]
Hello
I am using Reshade which has the same .dll file as Norbyte's Script Extender. So I would like to know if it's possible, how do I use Norbyte's Script Extender and Reshade at the same time?

**Comment by Norbyte** [comment]
Hi,

Yeah, simply rename the ReShade DXGI.dll to DXGINext.dll, and use the script extender's DLL as DXGI.dll.

**Comment by horizertical** [comment]
Hi,
Ok ! Thank you.. ^_^
