### ISSUE TITLE
Line of command error

### ISSUE THREAD

**Issue by hacksuya** [Norbyte/ositools#53]
![image](https://user-images.githubusercontent.com/79851136/109503935-cc84c800-7a92-11eb-9b31-1d69f7a5fd38.png)

**Comment by tkesterson** [comment]
im getting the same thing

**Comment by Norbyte** [comment]
Hi,

Those additional instructions are for Linux only; on Windows you don't have to change the Steam parameters, just have to place the DLL in the correct location.
