### ISSUE TITLE
Where can I find OsirisExtenderSettings.json for achievements?

### ISSUE THREAD

**Issue by marat569** [Norbyte/ositools#60]
Basically the title.

Where can I find OsirisExtenderSettings.json so I can enable achivs with mods?

Thank you!

**Comment by PinewoodPip** [comment]
It's in the DefEd/bin folder, same place where you've put DXGI.dll. That setting is enabled by default.

**Comment by Norbyte** [comment]
^ 
If the file is not there it means that the extender is running with default settings and the achievement setting is enabled.
Make sure that you don't use any other achievement enabler mod as they might conflict.

**Comment by marat569** [comment]
Ah thank you!

Do you know if it also works for lucky bag changes? I don't want to turn them on and rip my achivs!

**Comment by blackdarks** [comment]
Why can't I find the OsirisExtenderSettings.json file in Defed / bin directory
