### ISSUE TITLE
Getting version 54?

### ISSUE THREAD

**Issue by LuxLucian** [Norbyte/ositools#61]
I'm running the extender on Linux through proton, and I'm not sure how to get v54. The auto update does not appear to be working.

**Comment by Norbyte** [comment]
Hi,

There is a debug build of the updater available that has additional logging that should show why the update fails:
https://nb-stor.s3.eu-central-1.amazonaws.com/dos/OsiExtender/Devel/DXGIDebug.zip

**Comment by Norbyte** [comment]
In addition, you can always fetch the latest version manually if update is not working for some reason. Update URL for release channel is https://nb-stor.s3.eu-central-1.amazonaws.com/dos/OsiExtender/Release/Latest.zip

**Comment by LuxLucian** [comment]
Thank you for the information and helpful links. I think I'll stick to manually updating it for now.
