### ISSUE TITLE
Startup Launch Issue

### ISSUE THREAD

**Issue by WilliamIX** [Norbyte/ositools#66]
Set Launch Options:
![image](https://user-images.githubusercontent.com/332650/129105647-884075c7-cd14-4c7a-91bc-ca48cd5308e5.png)

Unzipped the DLL:
![image](https://user-images.githubusercontent.com/332650/129105974-8d294b85-c9c8-4c80-8796-563e910255f3.png)

Get an error:
![image](https://user-images.githubusercontent.com/332650/129106088-dd74a7f4-4f95-4364-bb61-d9364b59b17f.png)

**Comment by WilliamIX** [comment]
Update: by removing the launch option text, the game runs and "Script Extender V55" appears next to the divinity version after launch

**Comment by mdiasribeiro** [comment]
The launch options are for using proton (in linux). It seems you are using Windows.

**Comment by poopiehead6969** [comment]
![](https://i.gyazo.com/10c04d719622b9990a512745c45d69b2.png)

**Comment by yashtaev** [comment]
I just left `WINEDLLOVERRIDES="DXGI.dll"` and it seems to work

**Comment by LaughingLeader** [comment]
If this is on Windows, note you don't need any launch options (those are for Linux).
