### ISSUE TITLE
[Bug]: Lua state not initialized after returning to main menu

### ISSUE THREAD

**Issue by PinewoodPip** [Norbyte/ositools#76]
### Operating System

- [X] Windows
- [ ] Linux

### Extender Version

v55, v56

### Game Version

v3.6.117.3755

### Bug Summary

After returning to the main menu from a session, lua is no longer available. It works the first time you load into the main menu upon launching the game, but not anytime afterwards.

As such the script extender version next to the game version is no longer shown.

**Comment by Norbyte** [comment]
Should be fixed in v56 (Devel branch)

**Comment by PinewoodPip** [comment]
Confirmed to work, thanks.
