### ISSUE TITLE
unable to extract script extender update package

### ISSUE THREAD

**Issue by FlangeoftheElderGods** [Norbyte/ositools#8]
![20200320_170946](https://user-images.githubusercontent.com/62449399/77209654-2cc66800-6ad5-11ea-9238-57694232ea5d.jpg)

When I try to run the game with the script extender I see the attached error message.

**Comment by FlangeoftheElderGods** [comment]
Trying to run it under Win10.
Tried running it as Admin and also various compatibility modes.
I can download the file from the other issue further down the Issues list without any problem. I suspect this is something OS based?

**Comment by FlangeoftheElderGods** [comment]
Reinstalling windows resolved things, confirmed to be OS based.

**Comment by Norbyte** [comment]
I use the Windows builtin Zip extractor, so if for some reason the builtin Zip component doesn't work extraction fails. I'm not sure what breaks it, but I've seen this issue pop up a few times, so I'll consider using a separate Zip library for later versions.
