### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by Iam0ovo0** [Norbyte/ositools#92]
### Operating System

Windows

### Extender Version

v3 2022/07/14 (also tried on v52 and v51)

### Game Version

v3.6.69.4648

### Bug Summary

On game lauch in the middle of loading I get error message (screenshot added) and dont have a text near game version about Script Extender. Looked throught other issues reports and:
1. Tried to open links to cloudfront.net - I can open this links from my browser and I can download files from there.
2. Tried to ping cloudfron.net via cmd.exe - sent 4 and received 4 data packages with no errors in 44ms each one.
3. Tried to install Norbyte Script Extender via Leader Mod Manager - it writes that installation was successfull but when trying to lauch game i still get error of update and when loading save in game Script Extender seems to not work too cause im getting error message from LeaderLib like "STOP! A Story Compilation Error occured with your active mods. You may be missing mod dependencies. Mods will not work correctly!" and some mod functions dont work even that im sure that its not a mod problem.

I guess its not gonna work any time soon for me. So there is a question:
Is it possible to install Norbyte Script Extender manually? Not manually via Updater from releases but really manually via downloading files from somewhere and copying to some directory (or maybe executable file or something). Is it possible to install it without Updater? Can you give me a link to guide or other issue report where explained how to do this if its possible?

### Links

https://imgur.com/t2YJRRp

**Comment by abobusbobussosus** [comment]
I had same problem and i've found solution by accident.So just write link from error in browser , u will see some code , in line "url"  u will see link to zip file , download it (I had 2 links so i downloaded both and checked "version.txt" and then worked with latest version) Then rename OsiExtenderEoCApp.dll to dxgii.dll (not sure that it's necessary but im telling how i did it) and put it in DefEd\bin.If tou try to start the game it might fail cuz you don't have libprotobuf-lite.dll.You can find it in same zip file where you found OsiExtenderEoCApp.dll , just put it in the same folder with dxgi.dll.Im completly not sure what i've done but somehow it started working.I hope it will help you too

**Comment by Iam0ovo0** [comment]
> I had same problem and i've found solution by accident.So just write link from error in browser , u will see some code , in line "url" u will see link to zip file , download it (I had 2 links so i downloaded both and checked "version.txt" and then worked with latest version) Then rename OsiExtenderEoCApp.dll to dxgii.dll (not sure that it's necessary but im telling how i did it) and put it in DefEd\bin.If tou try to start the game it might fail cuz you don't have libprotobuf-lite.dll.You can find it in same zip file where you found OsiExtenderEoCApp.dll , just put it in the same folder with dxgi.dll.Im completly not sure what i've done but somehow it started working.I hope it will help you too

Yeah, thank you very much, it works. I totally forgot to try renaming .dll files in loaded archive.
