### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by Awrel** [Norbyte/ositools#99]
### Operating System

Windows

### Extender Version

v55

### Game Version

v3.6.64.2709

### Bug Summary

Yesterday game was working fine, i played for a couple of hours and then i closed, today whenever i launch the game it tells me that the Script Extender doesn`t support game versions below v3.6.117, please upgrade. i don`t know why this is happening since yesterday it worked and i noticed the last update was on the 17th.

**Comment by Norbyte** [comment]
It is possible to force the updater to use old extender versions. To do so, create a file named `ScriptExtenderUpdaterConfig.json` in `Divinity Original Sin 2\DefEd\bin` with the following contents:

```json
{
	"TargetVersion": "56.0.0.0"
}
```
